### ISSUE TITLE
允许客户端自定义包名

### ISSUE THREAD

**Issue by fsy2001** [OpenTreeHole/notification#7]
目前各平台的包名由服务器静态配置。然而各平台可能会有多个不同包名的客户端App，如iOS端目前有SwiftUI和Flutter两个版本共存。这种配置方式会让SwiftUI版收不到推送通知。因此，需要允许客户端在上传Token时自定义包名，并将包名与Token一同存储。为了兼容性，对于旧版App仍可采取静态配置的方式，即，对于没有附带包名的Token，使用各平台默认的包名推送通知。

**Comment by JingYiJun** [comment]
finished in https://github.com/OpenTreeHole/notification/commit/2d6a2592146b6daaee5bc27fd41567974997e191
